from  django.urls import path
from . import views
# django.contrib.auth import password_reset,password_reset_done,password_reset_confirm,password_reset_complete
urlpatterns=[
path('',views.load),
path('about',views.abt),
# path('login',views.log),
path('regn',views.regstn),
path('registran',views.registration),
path('loginruf',views.loginrf),
path('edit',views.user_edit_r),
path('lgin',views.logipge),
path('user_homeurl',views.user_home),
# path('user_home_page',views.user_home_page),
# path('logout_admin_view',views.logout_admin_view),

path('user_edit',views.profile_edit),
path('logut',views.logout_view),
path('admin123',views.admn_view),
path('regstn_admin',views.regstn_admn),
path('job_form',views.job_form),
path('jobs',views.job_updation),
path('approval',views.admin_aproval),
path('aply_job',views.apply_job),
path('contct',views.contact),
path('apply_jobs_user',views.apply_jobs_user_view),
path('admin_job_apply',views.admin_job_user_apply),
path('admin_job_alot',views.admin_job_allotmnt),
path('admin_job_alotmnt_submit',views.admin_job_alotmnt_submit),
path('notfcn',views.notification),
path('confirm_intrview',views.confirmation_user),
path('confirm',views.user_confirmed_jobs),
path('jobs_apply_user',views.jobs_details_for_user),
path('forgot',views.forgot),
path('password_reset',views.password_reset,name='password_reset'),
path('complted_intrview',views.complted_intrview),
path('home_jobs',views.home_jobs),
path('usr_complte_intrws',views.usr_complte_intrws),
path('usr_abort_intrws',views.usr_abort_intrws),
path('usr_decline_inrws',views.usr_decline_inrws),
path('usr_rjct_inrws',views.usr_rjct_inrws),
path('admin_job_view',views.admin_job_view),
path('dlte_admn_jobs',views.dlte_admn_jobs),
path('Expaired_jobs',views.Expaired_jobs),
path('aply_job_home',views.aply_job_home),
path('bck_home_admin',views.admn_view),
path('resume_pdf_view',views.pdf_view),
path('change_pswd', views.change_pswd),
path('change_passwrd',views.change_passwrd),
]