# Generated by Django 2.2.7 on 2020-02-08 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Apply_job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullnme', models.CharField(max_length=20)),
                ('mail', models.CharField(max_length=30)),
                ('msg', models.CharField(max_length=60)),
                ('resme_uplod', models.FileField(default=0, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Approved_users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=40)),
                ('lname', models.CharField(max_length=20)),
                ('gnder', models.CharField(max_length=2)),
                ('place', models.CharField(max_length=20)),
                ('emai', models.CharField(max_length=20)),
                ('phno', models.IntegerField()),
                ('expnce', models.CharField(max_length=20)),
                ('corse', models.CharField(max_length=20)),
                ('qulifcn', models.CharField(max_length=20)),
                ('pasout', models.IntegerField()),
                ('clge', models.CharField(max_length=40)),
                ('mark', models.IntegerField()),
                ('intrested_area', models.CharField(max_length=20)),
                ('status', models.IntegerField(default=1)),
            ],
            options={
                'db_table': 'aproved_users',
            },
        ),
        migrations.CreateModel(
            name='Jobs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designatn', models.CharField(max_length=40)),
                ('cmpny', models.CharField(max_length=40)),
                ('salary', models.IntegerField()),
                ('qualification', models.CharField(max_length=40)),
                ('place', models.CharField(max_length=40)),
                ('district', models.CharField(max_length=40)),
                ('dte', models.DateField()),
            ],
            options={
                'db_table': 'jobs_add',
            },
        ),
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=40)),
                ('lname', models.CharField(max_length=20)),
                ('gnder', models.CharField(max_length=2)),
                ('place', models.CharField(max_length=20)),
                ('emai', models.CharField(max_length=20)),
                ('phno', models.IntegerField()),
                ('expnce', models.CharField(max_length=20)),
                ('corse', models.CharField(max_length=20)),
                ('qulifcn', models.CharField(max_length=20)),
                ('pasout', models.IntegerField()),
                ('clge', models.CharField(max_length=40)),
                ('mark', models.IntegerField()),
                ('intrested_area', models.CharField(max_length=20)),
                ('status', models.IntegerField(default=1)),
            ],
            options={
                'db_table': 'registrn',
            },
        ),
    ]
