# Generated by Django 2.2.7 on 2020-02-08 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apply_job',
            name='resme_uplod',
            field=models.FileField(upload_to='documents'),
        ),
        migrations.AlterModelTable(
            name='apply_job',
            table='aply_job',
        ),
    ]
