# Generated by Django 2.2.7 on 2020-02-08 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online', '0002_auto_20200208_0319'),
    ]

    operations = [
        migrations.CreateModel(
            name='intrvew_schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=30)),
                ('desination', models.CharField(max_length=30)),
                ('company', models.CharField(max_length=30)),
                ('place', models.CharField(max_length=30)),
                ('distrct', models.CharField(max_length=30)),
                ('date', models.DateField()),
            ],
        ),
        migrations.AlterField(
            model_name='apply_job',
            name='resme_uplod',
            field=models.FileField(upload_to='media'),
        ),
    ]
