# Generated by Django 2.2.7 on 2020-02-08 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('online', '0004_auto_20200208_0639'),
    ]

    operations = [
        migrations.RenameField(
            model_name='intrvew_schedule',
            old_name='distrct',
            new_name='adres',
        ),
        migrations.RemoveField(
            model_name='intrvew_schedule',
            name='place',
        ),
    ]
