# Generated by Django 2.2.7 on 2020-02-12 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online', '0005_auto_20200208_1004'),
    ]

    operations = [
        migrations.CreateModel(
            name='scheduled_intrviw',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=30)),
                ('desination', models.CharField(max_length=30)),
                ('company', models.CharField(max_length=30)),
                ('adres', models.CharField(max_length=30)),
                ('status', models.CharField(default='Not Scheduled Yet', max_length=30)),
                ('date', models.DateField()),
            ],
            options={
                'db_table': 'interviw_scheduled',
            },
        ),
    ]
