# Generated by Django 2.2.7 on 2020-02-12 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('online', '0006_scheduled_intrviw'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='scheduled_intrviw',
            new_name='Intrview_scheduled_for_user',
        ),
    ]
