# Generated by Django 2.2.7 on 2020-02-12 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online', '0007_auto_20200212_1051'),
    ]

    operations = [
        migrations.AddField(
            model_name='intrview_scheduled_for_user',
            name='usr_status',
            field=models.CharField(default='Null', max_length=30),
        ),
    ]
