# Generated by Django 2.2.7 on 2020-02-12 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online', '0008_intrview_scheduled_for_user_usr_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rejected_applicatn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=30)),
                ('desination', models.CharField(max_length=30)),
                ('company', models.CharField(max_length=30)),
                ('adres', models.CharField(max_length=30)),
                ('status', models.CharField(default='Not Scheduled Yet', max_length=30)),
            ],
            options={
                'db_table': 'rejectd_applicn',
            },
        ),
    ]
