# Generated by Django 2.2.7 on 2020-02-13 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online', '0009_rejected_applicatn'),
    ]

    operations = [
        migrations.AddField(
            model_name='apply_job',
            name='company',
            field=models.CharField(default='null', max_length=30),
        ),
    ]
