# Generated by Django 2.2.7 on 2020-02-13 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online', '0010_apply_job_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='apply_job',
            name='desination',
            field=models.CharField(default='null', max_length=30),
        ),
    ]
