# Generated by Django 2.2.7 on 2020-02-19 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online', '0011_apply_job_desination'),
    ]

    operations = [
        migrations.AddField(
            model_name='intrview_scheduled_for_user',
            name='admin_status',
            field=models.CharField(default='No action', max_length=30),
        ),
    ]
