# Generated by Django 2.2.7 on 2020-02-19 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online', '0012_intrview_scheduled_for_user_admin_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='intrview_scheduled_for_user',
            name='admin_status',
        ),
        migrations.AddField(
            model_name='apply_job',
            name='admin_status',
            field=models.CharField(default='Not Scheduled Yet', max_length=30),
        ),
    ]
