# Generated by Django 2.2.7 on 2020-02-22 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online', '0013_auto_20200218_2141'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='approved_users',
            name='status',
        ),
        migrations.AddField(
            model_name='approved_users',
            name='admin_status',
            field=models.CharField(default='Not Approved', max_length=20),
        ),
    ]
