# Generated by Django 2.2.7 on 2020-02-27 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online', '0014_auto_20200222_0619'),
    ]

    operations = [
        migrations.AddField(
            model_name='intrview_scheduled_for_user',
            name='overall_status',
            field=models.CharField(default='No action', max_length=30),
        ),
    ]
