# Generated by Django 2.2.7 on 2020-06-23 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online', '0015_intrview_scheduled_for_user_overall_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobs',
            name='status',
            field=models.CharField(default='Not Expaired', max_length=40),
        ),
    ]
